import { Position } from "@/lib/portfolio-types";

/** 강희진 실제 보유 기준 시드 — 김도율·김찬율도 동일 수량·평단가로 복제 */
export const SEED_강희진_보유: Omit<Position, "owner">[] = [
  {
    symbol: "0022T0",
    name: "SOL 커버드콜",
    quantity: 1576,
    avgPrice: 14989,
    currentPrice: 15070,
    currency: "KRW",
    accountType: "국내주식",
    accountName: "국내주식-주계좌",
    chartGroup: "GOLD",
  },
  {
    symbol: "RMS",
    name: "에르메스",
    quantity: 4,
    avgPrice: 2084,
    currentPrice: 1622,
    currency: "EUR",
    purchaseEurKrw: 1532.78,
    accountType: "해외주식",
    accountName: "해외주식-유럽",
  },
  {
    symbol: "0118S0",
    name: "미국넥스트테크",
    quantity: 314,
    avgPrice: 10445,
    currentPrice: 9510,
    currency: "KRW",
    accountType: "국내주식",
    accountName: "국내주식-주계좌",
    chartGroup: "ATTACK",
  },
  {
    symbol: "0118Z0",
    name: "ACE 미국AI테크핵심산업액티브",
    quantity: 749,
    avgPrice: 10225,
    currentPrice: 7935,
    currency: "KRW",
    accountType: "국내주식",
    accountName: "국내주식-주계좌",
    chartGroup: "ATTACK",
  },
  {
    symbol: "218420",
    name: "KODEX 미국S&P500에너지",
    quantity: 202,
    avgPrice: 19475,
    currentPrice: 22400,
    currency: "KRW",
    accountType: "국내주식",
    accountName: "국내주식-주계좌",
    chartGroup: "XLE",
  },
  {
    symbol: "381180",
    name: "TIGER 미국필라델피아반도체나스닥",
    quantity: 70,
    avgPrice: 30622,
    currentPrice: 29665,
    currency: "KRW",
    accountType: "국내주식",
    accountName: "국내주식-주계좌",
    chartGroup: "AI",
  },
  {
    symbol: "487230",
    name: "KODEX 미국AI전력핵심인프라",
    quantity: 100,
    avgPrice: 20366,
    currentPrice: 19965,
    currency: "KRW",
    accountType: "국내주식",
    accountName: "국내주식-주계좌",
    chartGroup: "AI",
  },
  {
    symbol: "488500",
    name: "TIGER 미국S&P500동일가중",
    quantity: 693,
    avgPrice: 12548,
    currentPrice: 12105,
    currency: "KRW",
    accountType: "국내주식",
    accountName: "국내주식-주계좌",
    chartGroup: "S&P500",
  },
  {
    symbol: "494840",
    name: "TIGER 미국방산TOP10",
    quantity: 248,
    avgPrice: 16116,
    currentPrice: 14830,
    currency: "KRW",
    accountType: "국내주식",
    accountName: "국내주식-주계좌",
    chartGroup: "방산",
  },
  {
    symbol: "496770",
    name: "PLUS 글로벌방산",
    quantity: 185,
    avgPrice: 21586,
    currentPrice: 19770,
    currency: "KRW",
    accountType: "국내주식",
    accountName: "국내주식-주계좌",
    chartGroup: "방산",
  },
  {
    symbol: "M04020000",
    name: "금현물",
    quantity: 157,
    avgPrice: 222195,
    currentPrice: 221009,
    currency: "KRW",
    accountType: "국내주식",
    accountName: "국내주식-주계좌",
    chartGroup: "GOLD",
  },
];
